const sentences = [
"（（私（わたし）の大学（だいがく）は））東京大学（とうきょうだいがく）です。",
"（（私（わたし）は））高校（こうこう）に行（い）きます。",
"（（私（わたし）は））学生（がくせい）です。",
"（（私（わたし）は））大学院生（だいがくいんせい）です。",
"（（私（わたし）は））大学生（だいがくせい）です。",
"（（私（わたし）は））高校生（こうこうせい）です。",
"（（私（わたし）は））留学生（りゅうがくせい）です。",
"（（彼（かれ）は））先生（せんせい）です。",
"（（私は））三年生（さんねんせい）です。",
"（（私（わたし）の専攻（せんこう）は））経済学（けいざいがく）です。",
"私（わたし）は学生（がくせい）です。",
"（（彼（かれ）は））友達（ともだち）です。",
"（（田中（たなか））さんは学生（がくせい）です。",
"（（彼（かれ）は））日本人（にほんじん）です。",
"（（彼女（かのじょ）は））日本人（にほんじん）です。",
"（（今（いま）は））午前（ごぜん）十時（じゅうじ）です。",
"（（授業（じゅぎょう）は））午前（ごぜん）九時（くじ）に始（はじ）まります。",
"（（会議（かいぎ）は））午後（ごご）一時（いちじ）です。",
"（（今（いま）は））三時（さんじ）です。",
"（（今（いま）は））三時半（さんじはん）です。",
"日本（にほん）は美（うつく）しい国（くに）です。",
"アメリカ（あめりか）は大（おお）きい国（くに）です。",
"（（私は））英語（えいご）を話（はな）します。",
"（（私（わたし）は））日本語（にほんご）を学（まな）びます。",
"（（彼（かれ）は））電話（でんわ）をかけます。",
"（（私（わたし）の部屋（へや）は））二番（にばん）です。",
"（（電話（でんわ）の番号（ばんごう）は））1234です。",
"何（なに）を食（た）べますか。",
"（（私（わたし）の））お母（かあ）さんは優（やさ）しいです。",
"（（私（わたし）の））お父（とう）さんは強（つよ）いです。",
"（（私（わたし）の））お姉（ねえ）さんは賢（かしこ）いです。",
"（（私（わたし）の））お兄（にい）さんは背（せ）が高（たか）いです。",
"（（私（わたし）の））妹（いもうと）は可愛（かわい）いです。",
"（（私（わたし）の））弟（おとうと）は元気（げんき）です。",
"イギリス（いぎりす）は歴史（れきし）のある国（くに）です。",
"オーストラリア（おうすとらりあ）は大（おお）きな島（しま）です。",
"韓国（かんこく）は食（た）べ物（もの）が美味（おい）しいです。",
"カナダ（かなだ）は寒（さむ）い国（くに）です。",
"中国（ちゅうごく）は人口（じんこう）が多（おお）いです。",
"（（私（わたし）の専攻（せんこう）は））アジア（あじあ）研究（けんきゅう）です。",
"（（私（わたし）の専攻（せんこう）は））経済（けいざい）です。",
"（（私（わたし）の専攻（せんこう）は））工学（こうがく）です。",
"（（私（わたし）の専攻（せんこう）は））国際関係（こくさいかんけい）です。",
"（（私（わたし）の専攻（せんこう）は））コンピューター（こんぴゅうたあ）です。",
"（（私（わたし）の専攻（せんこう）は））政治（せいじ）です。",
"（（私（わたし）の専攻（せんこう）は））生物学（せいぶつがく）です。",
"（（私（わたし）の専攻（せんこう）は））ビジネス（びじねす）です。",
"（（私（わたし）の専攻（せんこう）は））文学（ぶんがく）です。",
"（（私（わたし）の専攻（せんこう）は））歴史（れきし）です。",
"（（彼（かれ）は））医者（いしゃ）です。",
"（（彼女（かのじょ）は））会社員（かいしゃいん）です。",
"（（彼女（かのじょ）は））看護師（かんごし）です。",
"（（彼女（かのじょ）は））主婦（しゅふ）です。",
"（（彼（かれ）は））弁護士（べんごし）です。",
]

const translations = [
"(My university is) Tokyo University.",
"(I) go to high school.",
"(I am) a student.",
"(I am) a graduate student.",
"(I am) a university student.",
"(I am) a high school student.",
"(I am) an exchange student.",
"(He is) a teacher.",
"(I am) a third-year student.",
"(My major is) economics.",
"I am a student.",
"(He is) a friend.",
"(Mr./Ms. Tanaka is) a student.",
"(He is) Japanese.",
"(She is) Japanese.",
"(It is now) 10 AM.",
"(The class starts at) 9 AM.",
"(The meeting is at) 1 PM.",
"(It is now) 3 o'clock.",
"(It is now) 3:30.",
"Japan is a beautiful country.",
"America is a large country.",
"(I speak) English.",
"(I am learning) Japanese.",
"(He makes a) phone call.",
"(My room is) number 2.",
"(The phone number is) 1234.",
"What will (you) eat?",
"(My) mother is kind.",
"(My) father is strong.",
"(My) older sister is smart.",
"(My) older brother is tall.",
"(My) younger sister is cute.",
"(My) younger brother is energetic.",
"England is a country with history.",
"Australia is a large island.",
"Korea has delicious food.",
"Canada is a cold country.",
"China has a large population.",
"(My major is) Asian studies.",
"(My major is) economics.",
"(My major is) engineering.",
"(My major is) international relations.",
"(My major is) computer science.",
"(My major is) politics.",
"(My major is) biology.",
"(My major is) business.",
"(My major is) literature.",
"(My major is) history.",
"(He is) a doctor.",
"(She is) an office worker.",
"(She is) a nurse.",
"(She is) a housewife.",
"(He is) a lawyer.",
]